services:
  tracker-tracker-app:
    # image: ghcr.io/jordanlambrecht/tracker-tracker:latest
    build: .
    restart: unless-stopped
    container_name: tracker-tracker-app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      POSTGRES_HOST: tracker-tracker-db
      # POSTGRES_PORT: ${POSTGRES_PORT} uncomment if you change the default port in the db service
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      TZ: ${TZ}
      LOG_LEVEL: ${LOG_LEVEL} # optional, defaults to 'info'
      LOG_FILE: /data/logs/tracker-tracker.log # optional
    volumes:
      - ./data:/data
    depends_on:
      tracker-tracker-db:
        condition: service_healthy

  tracker-tracker-db:
    image: postgres:17-alpine
    restart: unless-stopped
    container_name: tracker-tracker-db
    environment:
      POSTGRES_DB: tracker_tracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_PORT: ${POSTGRES_PORT} uncomment if you want to customize
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
